import pandas as pd
import os
import json
from groq import Groq

# Initialize Groq client
client = Groq(
    api_key=os.environ.get("GROQ_API_KEY"),
)

def get_dr_zhao_feedback(question, essay):
    """
    Placeholder function to integrate Dr. Zhao's model.
    Once you extract the .tar.gz file, import his function here.
    """
    # Example integration:
    # score, feedback = dr_zhao_model.predict(question, essay)
    # return feedback
    
    return "This is a placeholder for the AI feedback generated by Dr. Zhao's model."

def extract_atomic_statements(feedback_text):
    """
    Calls the Groq API to break down a paragraph of feedback into atomic statements.
    """
    prompt = f"""
    You are an expert educational analytics assistant specializing in rubric-based essay evaluation. 
    Your task is to deconstruct a block of feedback into a list of distinct, singular "atomic statements" for comparison.

    An atomic statement must:
    1. Contain exactly one complete observation, praise, or critique.
    2. Be completely self-contained.
    3. Be written in a concise, declarative format.

    Input Feedback text:
    \"\"\"
    {feedback_text}
    \"\"\"

    Analyze the feedback text above and map each atomic statement to one of the following rubric dimensions if applicable:
    - Interdisciplinary Integration (combining fields)
    - Evidence & Support
    - Structure & Flow
    - Language & Mechanics

    Respond strictly in JSON format matching this structure:
    {{
      "atomic_statements": [
        {{
          "statement": "The exact concise statement",
          "dimension": "The matched rubric dimension or 'General'"
        }}
      ]
    }}
    """

    try:
        chat_completion = client.chat.completions.create(
            messages=[
                {
                    "role": "user",
                    "content": prompt,
                }
            ],
            model="llama3-8b-8192", # Or whichever Groq model you prefer (e.g., mixtral-8x7b-32768)
            response_format={"type": "json_object"},
            temperature=0.1, # Low temperature for consistent JSON formatting
        )
        
        response_content = chat_completion.choices[0].message.content
        return json.loads(response_content)
    except Exception as e:
        print(f"Error calling Groq API: {e}")
        return None

def main():
    # 1. Load the dataset
    file_path = 'Interdisciplinary learning_labelled data_9 dimensions_283rows1.xlsx - Interdisciplinary learning_labe.csv'
    print(f"Loading data from {file_path}...")
    df = pd.read_csv(file_path)

    # 2. Extract only the first two columns (Index 0 and 1)
    # The snippet shows these are 'Assignment description' and 'Student Writing'
    essays_df = df.iloc[:, [0, 1]].copy()
    essays_df.columns = ['Question', 'Essay']
    
    print(f"Successfully loaded {len(essays_df)} rows. Starting processing...\n")

    # List to store the results
    processed_data = []

    # 3. Iterate through the rows (Testing with the first 3 rows so we don't burn through API limits instantly)
    for index, row in essays_df.head(3).iterrows():
        print(f"--- Processing Essay {index + 1} ---")
        question = row['Question']
        essay = row['Essay']

        # Step A: Run Dr. Zhao's Model to get the AI feedback
        ai_feedback = get_dr_zhao_feedback(question, essay)
        
        # Step B: Break down the AI feedback into atomic statements using Groq
        ai_atomic_statements = extract_atomic_statements(ai_feedback)
        
        # (Later, you will also pass the human feedback from the original CSV into the extract_atomic_statements function)
        
        # Store the results
        result = {
            "essay_id": index + 1,
            "question": question,
            "essay_snippet": essay[:100] + "...", # Just saving a snippet for the log
            "raw_ai_feedback": ai_feedback,
            "ai_atomic_statements": ai_atomic_statements
        }
        processed_data.append(result)
        print(f"Successfully extracted {len(ai_atomic_statements.get('atomic_statements', []))} statements.\n")

    # 4. Save the processed output to a new file
    output_file = 'processed_atomic_statements.json'
    with open(output_file, 'w') as f:
        json.dump(processed_data, f, indent=4)
        
    print(f"Processing complete. Results saved to {output_file}")

if __name__ == "__main__":
    main()